{{- if .Values.clusterRole.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.names.role }}
  labels:
    {{- include "ephemerator.labels" . | nindent 4 }}
  {{- with .Values.clusterRole.annotations.role }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: ["tessellate.io"]
  resources: ["ephemerators"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
{{- end }}