chart-dirs:
  - charts
chart-repos:
  - tesellate=https://awaldow.github.io/tesellate-helm
remote: origin
target-branch: main
helm-extra-args: --timeout 600s
check-version-increment: true
validate-chart-schema: true
validate-yaml: true
validate-maintainers: true