apiVersion: v1
kind: Service
metadata:
  name: {{ include "ephemerator.fullname" . }}
  labels:
    {{- include "ephemerator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
    # - port: 443
    #   targetPort: 8443
    #   protocol: TCP
    #   name: admission-webhook
  selector:
    {{- include "ephemerator.selectorLabels" . | nindent 4 }}
